obj-m   += enfs.o

#EXTRA_CFLAGS += -I$(PWD)/..

enfs-y := enfs_init.o
enfs-y += enfs_config.o
enfs-y += mgmt_init.o
enfs-y += enfs_multipath_client.o
enfs-y += enfs_multipath_parse.o
enfs-y += failover_path.o
enfs-y += failover_time.o
enfs-y += enfs_roundrobin.o
enfs-y += enfs_multipath.o
enfs-y += enfs_path.o
enfs-y += enfs_proc.o
enfs-y += enfs_remount.o
enfs-y += pm_ping.o
enfs-y += pm_state.o
