# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_XCU_VSTREAM) += vstream.o
obj-$(CONFIG_XCU_SCHEDULER) += core.o
obj-$(CONFIG_XCU_SCHED_RT) += rt.o
obj-$(CONFIG_XCU_SCHED_CFS) += cfs.o
obj-$(CONFIG_CGROUP_XCU) += cgroup.o
